<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AddBankIdToQuotes' => $baseDir . '/database/migrations/2021_10_28_045042_add_bank_id_to_quotes.php',
    'AddClientrefToLeads' => $baseDir . '/database/migrations/2021_10_15_045913_add_clientref_to_leads.php',
    'AddRevisionToQuotes' => $baseDir . '/database/migrations/2021_10_25_092316_add_revision_to_quotes.php',
    'AddStatusToLeads' => $baseDir . '/database/migrations/2021_10_12_075849_add_status_to_leads.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'CreateCustomerBranchesTable' => $baseDir . '/database/migrations/2021_10_30_023501_create_customer_branches_table.php',
    'Database\\DisableForeignKeys' => $baseDir . '/database/DisableForeignKeys.php',
    'Database\\Schema\\BlueprintLibrary' => $baseDir . '/database/Schema/BlueprintLibrary.php',
    'Database\\Seeders\\DatabaseSeeder' => $baseDir . '/database/seeders/DatabaseSeeder.php',
    'Database\\TruncateTable' => $baseDir . '/database/TruncateTable.php',
    'InsertSampleDataToCustomerBranchesTable' => $baseDir . '/database/migrations/2021_10_30_043157_insert_sample_data_to_customer_branches_table.php',
    'RemoveConversionRateFromQuotes' => $baseDir . '/database/migrations/2021_10_19_054150_remove_conversion_rate_from_quotes.php',
    'UpdateBranchIdInLeads' => $baseDir . '/database/migrations/2021_10_28_180806_update_branch_id_in_leads.php',
);
